// This file is auto-generated by src/integrations/icons/utils/generate-icon-map.mjs.
// Do not edit manually. Run "npm run generate:icons" (or node src/integrations/icons/utils/generate-icon-map.mjs) to regenerate.

import type { IconType } from 'react-icons';
import { FaAmazon, FaApple, FaArrowsUpDownLeftRight, FaBook, FaBookOpen, FaBullseye, FaChartSimple, FaClockRotateLeft, FaCompass, FaDiscord, FaEye, FaFeather, FaFileLines, FaGooglePlay, FaGraduationCap, FaHeadphones, FaHeadset, FaLayerGroup, FaLifeRing, FaLink, FaPalette, FaRobot, FaRotateLeft, FaScaleBalanced, FaShieldHalved, FaSpotify, FaTabletScreenButton, FaUniversalAccess, FaWandMagicSparkles, FaXmark } from 'react-icons/fa6';
import { LuArrowRight, LuBookOpen, LuChevronRight, LuContact, LuGlobe, LuImage, LuMail, LuPhone, LuSettings } from 'react-icons/lu';
import { SiDiscord, SiInstagram, SiTiktok, SiX, SiYoutube } from 'react-icons/si';

export const iconMap = {
  'fa6:amazon': FaAmazon,
  'fa6:apple': FaApple,
  'fa6:arrows-up-down-left-right': FaArrowsUpDownLeftRight,
  'fa6:book': FaBook,
  'fa6:book-open': FaBookOpen,
  'fa6:bullseye': FaBullseye,
  'fa6:chart-simple': FaChartSimple,
  'fa6:clock-rotate-left': FaClockRotateLeft,
  'fa6:compass': FaCompass,
  'fa6:discord': FaDiscord,
  'fa6:eye': FaEye,
  'fa6:feather': FaFeather,
  'fa6:file-lines': FaFileLines,
  'fa6:google-play': FaGooglePlay,
  'fa6:graduation-cap': FaGraduationCap,
  'fa6:headphones': FaHeadphones,
  'fa6:headset': FaHeadset,
  'fa6:layer-group': FaLayerGroup,
  'fa6:life-ring': FaLifeRing,
  'fa6:link': FaLink,
  'fa6:palette': FaPalette,
  'fa6:robot': FaRobot,
  'fa6:rotate-left': FaRotateLeft,
  'fa6:scale-balanced': FaScaleBalanced,
  'fa6:shield-halved': FaShieldHalved,
  'fa6:spotify': FaSpotify,
  'fa6:tablet-screen-button': FaTabletScreenButton,
  'fa6:universal-access': FaUniversalAccess,
  'fa6:wand-magic-sparkles': FaWandMagicSparkles,
  'fa6:xmark': FaXmark,
  'lu:arrow-right': LuArrowRight,
  'lu:book-open': LuBookOpen,
  'lu:chevron-right': LuChevronRight,
  'lu:contact': LuContact,
  'lu:globe': LuGlobe,
  'lu:image': LuImage,
  'lu:mail': LuMail,
  'lu:phone': LuPhone,
  'lu:settings': LuSettings,
  'si:discord': SiDiscord,
  'si:instagram': SiInstagram,
  'si:tiktok': SiTiktok,
  'si:x': SiX,
  'si:youtube': SiYoutube,
} satisfies Record<string, IconType>;

export type IconKey = keyof typeof iconMap;
